#### #### DO NOT EDIT THIS FILE ##### ####
#requires -version 2.0
$script:ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

#$psversiontable.psversion
$thisScript = Split-Path -Path $MyInvocation.MyCommand.Definition -Parent
. ($thisScript + '\download_unzip.ps1')

$downloadFolder='\'+$env:DOWNLOAD_FOLDER
$packageFolder='\'+$env:PACKAGE_FOLDER
$toolsFolder='\'+$env:TOOLS_FOLDER
$wixFolder='\'+$env:WIX_FOLDER

if (Test-Path -path ($thisScript+$packageFolder)){
Remove-Item -Recurse -Force ($thisScript+$packageFolder)}

if (Test-Path -path ($thisScript+$downloadFolder)){
Remove-Item -Recurse -Force ($thisScript+$downloadFolder)
}

$garbage = New-Item -ItemType directory -Path ($thisScript+$downloadFolder)
$garbage = New-Item -ItemType directory -Path ($thisScript+$packageFolder)
$garbage = New-Item -ItemType directory -Path ($thisScript+$toolsFolder)
$garbage = New-Item -ItemType directory -Path ($thisScript+$wixFolder)

$garbage = DownloadFile $env:ES_DIST_DOWNLOAD_URL
$garbage = DownloadFile $env:JAVA_DIST_DOWNLOAD_URL
$garbage = DownloadFile $env:WIX_DIST_DOWNLOAD_URL

Unzip ($thisScript+$downloadFolder+"\"+(Split-Path -Path ([System.Uri]$env:ES_DIST_DOWNLOAD_URL).LocalPath -leaf)) ($thisScript + $packageFolder)
Unzip ($thisScript+$downloadFolder+"\"+(Split-Path -Path ([System.Uri]$env:WIX_DIST_DOWNLOAD_URL).LocalPath -leaf))  ($thisScript + $wixFolder)
Untgz ($thisScript+$downloadFolder+"\"+(Split-Path -Path ([System.Uri]$env:JAVA_DIST_DOWNLOAD_URL).LocalPath -leaf))  ($thisScript + $packageFolder)

Rename-Item -path ($thisScript + $packageFolder+ "\"+ $env:JAVA_FOLDER_NAME) -newName ($thisScript + $packageFolder+ "\jdk")
Copy-Item ($thisScript + '\src\*.*') ($thisScript + $packageFolder+ '\'+$env:ES_DIST_NAME+'\bin\')