@echo off

rem set proxy, if needed, to download elasticsearch/java and plugins 
rem set HTTP_PROXY=http://proxy.domain.com:port
rem set HTTP_PROXY=http://webproxy1.pta.de:80

set ESI_VERSION=4

rem set JAVA Version
set JAVA_DIST_VERSION=7u51
rem set JAVA_DIST_VERSION_PATCHLEVEL=b13
set JAVA_DIST_NAME=server-jre-%JAVA_DIST_VERSION%-windows-x64
set JAVA_FOLDER_NAME=jdk1.7.0_51
set JAVA_DIST_DOWNLOAD_URL=http://saly.de/%JAVA_DIST_NAME%.tar.gz
rem set JAVA_DIST_DOWNLOAD_URL=http://localhost:8010/%JAVA_DIST_NAME%.tar.gz

rem set Elasticsearch Version
set ES_DIST_VERSION=0.90.13
set ES_DIST_NAME=elasticsearch-%ES_DIST_VERSION%
set ES_DIST_DOWNLOAD_URL=https://download.elasticsearch.org/elasticsearch/elasticsearch/%ES_DIST_NAME%.zip
rem set ES_DIST_DOWNLOAD_URL=http://localhost:8010/%ES_DIST_NAME%.zip

rem set WIX version
set WIX_DIST_VERSION=3.8
set WIX_DIST_DOWNLOAD_URL=http://saly.de/wix38-binaries.zip
rem set WIX_DIST_DOWNLOAD_URL=http://localhost:8010/wix38-binaries.zip

rem #### #### DO NOT EDIT THIS FILE BELOW THIS LINE ##### ####

VERIFY OTHER 2>nul
SETLOCAL ENABLEEXTENSIONS
IF ERRORLEVEL 1 ((ECHO Fatal: Unable to enable cmd extensions!) & (goto :eof))
ENDLOCAL

set GENERATED_TOP_FOLDER=target
set DOWNLOAD_FOLDER=%GENERATED_TOP_FOLDER%\download
set PACKAGE_FOLDER_NAME=content
set PACKAGE_FOLDER=%GENERATED_TOP_FOLDER%\%PACKAGE_FOLDER_NAME%
set TOOLS_FOLDER=%GENERATED_TOP_FOLDER%\tools
set WIX_FOLDER=%TOOLS_FOLDER%\WIX-%WIX_DIST_VERSION%

IF DEFINED HTTP_PROXY (goto setproxy) else (goto :eof)

:setproxy
for /f "tokens=1,2,3 delims=/:" %%a in ("%HTTP_PROXY%") do set protocol=%%a&set host=%%b&set port=%%c
set JAVA_OPTS=%JAVA_OPTS% -D%protocol%.proxyHost=%host% -D%protocol%.proxyPort=%port%