rem set proxy if needed
set JAVA_OPTS=%JAVA_OPTS% -Dhttp.proxyHost=webproxy1.pta.de -Dhttp.proxyPort=80

set ESI_VERSION=1

rem set JAVA Version
set JAVA_DIST_VERSION=7u45
set JAVA_DIST_VERSION_PATCHLEVEL=b18
set JAVA_DIST_NAME=server-jre-%JAVA_DIST_VERSION%-windows-x64
set JAVA_FOLDER_NAME=jdk1.7.0_45
set JAVA_DIST_DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/%JAVA_DIST_VERSION%-%JAVA_DIST_VERSION_PATCHLEVEL%/%JAVA_DIST_NAME%.tar.gz

rem set Elasticsearch Version
set ES_DIST_VERSION=0.90.5
set ES_DIST_NAME=elasticsearch-%ES_DIST_VERSION%
set ES_DIST_DOWNLOAD_URL=https://download.elasticsearch.org/elasticsearch/elasticsearch/%ES_DIST_NAME%.zip

rem set WIX version
set WIX_DIST_VERSION=3.8
set WIX_DIST_DOWNLOAD_URL=http://wixtoolset.org/downloads/v3.8.1014.0/wix38-binaries.zip

rem #### #### DO NOT EDIT THIS FILE BELOW THIS LINE ##### ####
set GENERATED_TOP_FOLDER=target
set DOWNLOAD_FOLDER=%GENERATED_TOP_FOLDER%\download
set PACKAGE_FOLDER_NAME=content
set PACKAGE_FOLDER=%GENERATED_TOP_FOLDER%\%PACKAGE_FOLDER_NAME%
set TOOLS_FOLDER=%GENERATED_TOP_FOLDER%\tools
set WIX_FOLDER=%TOOLS_FOLDER%\WIX-%WIX_DIST_VERSION%