@echo off
rem #### #### DO NOT EDIT THIS FILE ##### ####
rem Copyright 2014-2015 Hendrik Saly
rem Licensed under the Apache License, Version 2.0

call "%~dp0config.cmd"
IF NOT DEFINED GENERATED_TOP_FOLDER (goto badenv)
echo.
echo *** Starting phase "DUPC" (Download Unzip Pre Config) for ESI-%ES_DIST_VERSION%.%ESI_VERSION%-j%JAVA_DIST_VERSION% ***
if NOT "%host%" == "" echo Will use proxy %host%:%port% for all downloads 
echo.
rmdir /s /q "%~dp0%GENERATED_TOP_FOLDER%" >NUL 2>&1

if not defined ProgramFiles(x86) (
    
    echo 32-bit Windows is not supported. Please use a 64bit Operating System.
    goto:eof
)

rem 64bit powershell
set POWERSHELL_CMD="%windir%\System32\WindowsPowerShell\v1.0\powershell.exe" 
%POWERSHELL_CMD% -version 2.0 .\build_installer.ps1

if not %errorlevel% == 0  (
    echo If you run into problems with powershell make sure "Unresticted" execution policy is set.
    echo You can do this by open %POWERSHELL_CMD% and enter 'Set-ExececutionPolicy Unrestricted'
    goto :eof
) 

set OLD_PWD=%CD%
cd "%~dp0%PACKAGE_FOLDER%\%ES_DIST_NAME%\bin"

call "%~dp0esidist_plugininstall.bat" 1>NUL

cd %OLD_PWD%
echo.
echo Finished with phase "DUPC" (Download Unzip Pre Config)
echo You should now revise the stuff in folder 
echo     "%~dp0%PACKAGE_FOLDER%\%ES_DIST_NAME%\bin"
echo     "%~dp0%PACKAGE_FOLDER%\%ES_DIST_NAME%\config"
echo.
echo Then run "MKMSI.cmd" to build the .msi package (Phase MKMSI - Make MSI)
echo.
rem pause
goto :eof

:badenv
echo Bad environment, check config.cmd
rem pause