@echo off
rem #### #### DO NOT EDIT THIS FILE ##### ####
call "%~dp0config.cmd"
echo.
echo *** Starting phase "DUPC" (Download Unzip Pre Config) for ESI-%ES_DIST_VERSION%.%ESI_VERSION%-j%JAVA_DIST_VERSION% ***
if NOT "%host%" == "" echo Will use proxy %host%:%port% for all downloads 
echo.
rmdir /s /q "%~dp0%GENERATED_TOP_FOLDER%" >NUL 2>&1

powershell -version 2.0 .\build_installer.ps1

set OLD_PWD=%CD%
cd "%~dp0%PACKAGE_FOLDER%\%ES_DIST_NAME%\bin"
call "%~dp0esidist_plugininstall.bat" 1>NUL

cd %OLD_PWD%
echo.
echo Finished with phase "DUPC" (Download Unzip Pre Config)
echo You should now revise the stuff in folder 
echo     "%~dp0%PACKAGE_FOLDER%\%ES_DIST_NAME%\bin"
echo     "%~dp0%PACKAGE_FOLDER%\%ES_DIST_NAME%\config"
echo.
echo Then run "MKMSI.cmd" to build the .msi package (Phase MKMSI - Make MSI)
echo.
pause
