@echo off
rem #### #### DO NOT EDIT THIS FILE ##### ####
call "%~dp0\config.cmd"

echo Starting phase "DUPC" (Download Unzip Pre Config)

rmdir "%~dp0\%GENERATED_TOP_FOLDER%" /s /q > NUL 2>&1

powershell -version 2.0 .\build_installer.ps1

set OLD_PWD=%CD%
cd "%~dp0\%PACKAGE_FOLDER%\%ES_DIST_NAME%\bin"
call "%~dp0\esidist_plugininstall.bat"  > NUL

cd %OLD_PWD%
echo Finished with phase "DUPC" (Download Unzip Pre Config)
echo You should now revise the stuff in folder 
echo     "%~dp0\%PACKAGE_FOLDER%\%ES_DIST_NAME%\bin"
echo     "%~dp0\%PACKAGE_FOLDER%\%ES_DIST_NAME%\config"

echo Then run "MKMSI.cmd" to build the .msi package (Phase MKMSI - Make MSI)
pause