@echo off
rem #### #### DO NOT EDIT THIS FILE ##### ####
call "%~dp0\config.cmd"

IF EXIST "%~dp0\%PACKAGE_FOLDER%" (goto exists) else goto notexists

:notexists
echo Execute DUPC.cmd first
pause
goto eof

:exists
set WIX_HOME="%~dp0\%WIX_FOLDER%"
set ROOT="%~dp0\%PACKAGE_FOLDER%"
set TEMP="%~dp0\%WIX_FOLDER%"
set MSI_FOLDER="%~dp0\%GENERATED_TOP_FOLDER%\msi"

rmdir %MSI_FOLDER% /s /q > NUL 2>&1

echo Starting phase "MKMSI" (Make MSI)

%WIX_HOME%\heat.exe dir %ROOT% -cg MyFiles -gg -scom -sreg -sfrag -dr INSTALLDIR -out %TEMP%\FileFragment.wxs -var var.InstallerPath > NUL
	
%WIX_HOME%\candle.exe -dInstallerPath=%ROOT% -dEsiVersion=%ES_DIST_VERSION%.%ESI_VERSION% -dEsFolder=%PACKAGE_FOLDER_NAME%\%ES_DIST_NAME%  -dPlatform=x86 -arch x86  -out %TEMP%\ %TEMP%\FileFragment.wxs  Product.wxs  > NUL
  
%WIX_HOME%\light.exe -out %MSI_FOLDER%\ESI-%ES_DIST_VERSION%.%ESI_VERSION%-j%JAVA_DIST_VERSION%.msi -cultures:null -spdb -sval  %TEMP%\FileFragment.wixobj %TEMP%\Product.wixobj > NUL

echo Finished with phase "MKMSI" (Make MSI)
echo You should now find your final .msi file here: %MSI_FOLDER%
pause
